LESF MIP update using CVTool V2
WCRP-CMIP/CMIP6Plus_CVs pull request #18
Opened 2023-11-03 02:26 UTC by wolfiex

2023-11-03 02:41 UTC, durack1 requested changes
These changes would be useful

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_activity_id.json
> +            "long_name": "The Large Ensemble Single Forcing Model Intercomparison Project"
This might need a tweak

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +        "CMIP6Plus_CVS dir": {
"CMIP6Plus_CVs dir"? Is this correct, seems to be like a placeholder

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +            "min_number_yrs_per_sim": 36,
Should probably bump this to current, so 1979-2022 `min_number_yrs_per sim = 43` - the latest PCMDI-AMIP data would allow this, but maybe not all forcings, so 2014 may still be the cutoff

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +            "experiment": "pre-industrial control simulation with CO2 concentration calculated",
We should update this to "pre-industrial control simulation with preindustrial CO2 emissions defined  (CO2 emission-driven)"

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +            "experiment": "all-forcing simulation of the recent past with atmospheric CO2 concentration calculated",
"all-forcing simulation of the recent past with atmospheric CO2 concentration calculated (CO2 emission-driven)"

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +            "experiment": "all-forcing simulation of the recent past",
"all-forcing simulation of the recent past (CO2 concentration-driven)"

2023-11-03 02:41 UTC, durack1 commented on CMIP6Plus_experiment_id.json
> +            "experiment": "pre-industrial control",
"pre-industrial control (CO2 concentration-driven)"

2023-11-03 02:49 UTC, wolfiex commented on CMIP6Plus_activity_id.json
> +            "long_name": "The Large Ensemble Single Forcing Model Intercomparison Project"
Already on it. Liking the automatic 'outdated' tag.

2023-11-12 23:15 UTC, wolfiex commented
Automated CV generation by GitHub Action has been implemented here: 
https://github.com/WCRP-CMIP/CMIP6Plus_CVs/blob/lesfII/CVs/CV.json

To do:  
 - [ ] Populate the `version_metadata` string completely. - Do we want this to flattened into a delimited string?

2023-11-16 17:59 UTC, wolfiex commented
Squashed commits for merging.

2023-11-16 17:59 UTC, closed without merging